server:
  port: 8092

management:
  server:
    port: 8093

spring:
  jpa:
    show-sql: true
  kafka:
    properties:
      schema.registry.url: http://localhost:8085

  cloud:
    openfeign:
      client:
        config:
          customers:
            url: http://localhost:8094
