### Success use case
POST http://localhost:8092/v1/orders
Content-Type: application/json

{
  "customerId": "a13dfdb8-6e30-4d31-99e4-62c3a308e310",
  "orderCurrency": "USD",
  "orderItems": [
    {
      "productId": "c58b7367-207a-471c-b000-13f67f20c9ca",
      "price": {
        "value": "24.12",
        "currency": "EUR"
      },
      "weight": {
        "value": 0.12,
        "unit": "KG"
      },
      "quantity": 2
    }
  ],
  "discountCoupon": "ABC20"
}

### Product out of order use case
POST http://localhost:8092/v1/orders
Content-Type: application/json

{
  "customerId": "a13dfdb8-6e30-4d31-99e4-62c3a308e310",
  "orderCurrency": "USD",
  "orderItems": [
    {
      "productId": "3b1ad028-d67b-4ea4-a7eb-c51b268b277e",
      "price": {
        "value": "24.12",
        "currency": "EUR"
      },
      "weight": {
        "value": 0.12,
        "unit": "KG"
      },
      "quantity": 2
    }
  ],
  "discountCoupon": "ABC20"
}

###
GET http://localhost:8092/v1/orders

###
GET http://localhost:8092/v1/orders?customerId=a13dfdb8-6e30-4d31-99e4-62c3a308e310

###
GET http://localhost:8092/v1/orders/6c687337-603e-460e-b8d5-a8029503951d

###
GET http://localhost:8092/v1/orders/b07bf88c-8fe0-4e9f-b6e4-3001142d6d1c/items

###
PUT http://localhost:8092/v1/orders/dd00722c-0714-4d4e-92ae-9f379bac6cd4/send

###
PUT http://localhost:8092/v1/orders/0378904a-783f-44e0-ad58-5871e1999340/cancel
Content-Type: application/json

{
  "reason": "customer disposition"
}
